"""Add publish_record table for tracking flow publications

Revision ID: 2a32c0912c60
Revises: 3162e83e485f
Create Date: 2025-11-10 14:53:33.181445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langbuilder.utils import migration


# revision identifiers, used by Alembic.
revision: str = '2a32c0912c60'
down_revision: Union[str, None] = '3162e83e485f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    # Check if table already exists
    if 'publish_record' in inspector.get_table_names():
        # Table exists - ensure all constraints are present
        existing_constraints = {c['name'] for c in inspector.get_unique_constraints('publish_record')}
        existing_indexes = {idx['name'] for idx in inspector.get_indexes('publish_record')}

        with op.batch_alter_table('publish_record', schema=None) as batch_op:
            # Add missing unique constraint on id
            if 'uq_publish_record_id' not in existing_constraints:
                batch_op.create_unique_constraint('uq_publish_record_id', ['id'])

            # Add missing unique constraint for active publication
            if 'unique_active_publication' not in existing_constraints:
                batch_op.create_unique_constraint('unique_active_publication', ['flow_id', 'platform', 'platform_url', 'status'])

            # Add missing indexes
            if 'ix_publish_record_flow_id' not in existing_indexes:
                batch_op.create_index(batch_op.f('ix_publish_record_flow_id'), ['flow_id'], unique=False)
            if 'ix_publish_record_platform' not in existing_indexes:
                batch_op.create_index(batch_op.f('ix_publish_record_platform'), ['platform'], unique=False)
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publish_record',
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('published_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'UNPUBLISHED', 'ERROR', 'PENDING', name='publish_status_enum'), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_id', 'platform', 'platform_url', 'status', name='unique_active_publication'),
    sa.UniqueConstraint('id', name='uq_publish_record_id')
    )
    with op.batch_alter_table('publish_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publish_record_flow_id'), ['flow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publish_record_platform'), ['platform'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publish_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publish_record_platform'))
        batch_op.drop_index(batch_op.f('ix_publish_record_flow_id'))

    op.drop_table('publish_record')
    # ### end Alembic commands ###
