"""init postgres schema

Revision ID: 532b97986d7f
Revises: 
Create Date: 2026-01-09 17:04:02.456931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langbuilder.utils import migration


# revision identifiers, used by Alembic.
revision: str = '532b97986d7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=False),
    sa.Column('edit', sa.Boolean(), nullable=False),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('content_blocks', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flow_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vertex_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('store_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('optins', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('vertex_build',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('artifacts', sa.JSON(), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('build_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('build_id')
    )
    op.create_table('apikey',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_uses', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('apikey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apikey_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_apikey_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_apikey_user_id'), ['user_id'], unique=False)

    op.create_table('file',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('folder',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('auth_settings', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='unique_folder_name')
    )
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_folder_name'), ['name'], unique=False)

    op.create_table('variable',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_fields', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_bg_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gradient', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_component', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('webhook', sa.Boolean(), nullable=True),
    sa.Column('endpoint_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mcp_enabled', sa.Boolean(), nullable=True),
    sa.Column('action_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action_description', sa.Text(), nullable=True),
    sa.Column('access_type', sa.Enum('PRIVATE', 'PUBLIC', name='access_type_enum'), server_default=sa.text("'PRIVATE'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('fs_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id', 'endpoint_name', name='unique_flow_endpoint_name'),
    sa.UniqueConstraint('user_id', 'name', name='unique_flow_name')
    )
    with op.batch_alter_table('flow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flow_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_endpoint_name'), ['endpoint_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_flow_user_id'), ['user_id'], unique=False)

    op.create_table('publish_record',
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'UNPUBLISHED', 'ERROR', 'PENDING', name='publish_status_enum'), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_id', 'platform', 'platform_url', 'status', name='unique_active_publication'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('publish_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publish_record_flow_id'), ['flow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publish_record_platform'), ['platform'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publish_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publish_record_platform'))
        batch_op.drop_index(batch_op.f('ix_publish_record_flow_id'))

    op.drop_table('publish_record')
    with op.batch_alter_table('flow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flow_user_id'))
        batch_op.drop_index(batch_op.f('ix_flow_name'))
        batch_op.drop_index(batch_op.f('ix_flow_folder_id'))
        batch_op.drop_index(batch_op.f('ix_flow_endpoint_name'))
        batch_op.drop_index(batch_op.f('ix_flow_description'))

    op.drop_table('flow')
    op.drop_table('variable')
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folder_name'))

    op.drop_table('folder')
    op.drop_table('file')
    with op.batch_alter_table('apikey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apikey_user_id'))
        batch_op.drop_index(batch_op.f('ix_apikey_name'))
        batch_op.drop_index(batch_op.f('ix_apikey_api_key'))

    op.drop_table('apikey')
    op.drop_table('vertex_build')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('transaction')
    op.drop_table('message')
    # ### end Alembic commands ###
