import sys
sys.path.insert(0, '/Users/ather/Developer/PwC/Motherson/new_agentcore_final_publish/aimldevteam/agentcore/src/backend/base')

from alembic.config import Config
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected

alembic_cfg = Config("src/backend/base/agentcore/alembic.ini")
alembic_cfg.set_main_option("script_location", "src/backend/base/agentcore/alembic")
alembic_cfg.set_main_option("sqlalchemy.url", "postgresql+psycopg://postgres:postgres@localhost:5432/agentcore")

print("Running alembic check...")
print("script_location ->", alembic_cfg.get_main_option("script_location"))
print("using DATABASE_URL ->", alembic_cfg.get_main_option("sqlalchemy.url"))
try:
    command.check(alembic_cfg)
    print("\n✓ Alembic check passed: No schema diffs detected!")
except AutogenerateDiffsDetected as e:
    print(f"\nAlembic check failed: {e}")
    sys.exit(1)
except Exception as e:
    print(f"\nError: {e}")
    sys.exit(1)
